"""API endpoints for generating and retrieving tailored CVs."""

import uuid
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, Request, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.agents.cv_agent import process_cv_generation
from app.database import get_db
from app.models.generated_cv import GeneratedCV
from app.models.profile import Profile
from app.models.user import User
from app.schemas.cv import CVGenerateRequest, CVListItem, CVResponse
from app.schemas.profile import ProfileResponse, PersonalInfo
from app.security.jwt import get_current_user
from app.security.rate_limiter import limiter
from app.services.pdf_builder import generate_cv_pdf
from app.utils.file_handler import get_generated_cv_path

router = APIRouter(prefix="/cv", tags=["CV Generation"])


@router.post(
    "/generate",
    response_model=CVResponse,
    summary="Generate a tailored ATS CV from a job description",
)
@limiter.limit("5/minute")
async def generate_cv(
    request: Request,
    data: CVGenerateRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> CVResponse:
    """Generates a highly tailored CV based on the user's profile and the provided job description."""
    
    # 1. Fetch user's parsed profile
    db_result = await db.execute(select(Profile).where(Profile.user_id == current_user.id))
    profile = db_result.scalar_one_or_none()
    
    if not profile:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No resume profile found. Please upload a resume first.",
        )
        
    profile_response = ProfileResponse.model_validate(profile)
    
    # 2. Run the LangGraph agent
    result = await process_cv_generation(profile_response, data)
    
    if result.get("error") or not result.get("tailored_cv"):
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=result.get("error") or "Failed to generate CV content.",
        )
        
    tailored_cv = result["tailored_cv"]
    
    # 3. Generate PDF
    cv_id = uuid.uuid4()
    pdf_filename = f"CV_{data.company_name or 'Tailored'}_{cv_id}.pdf"
    pdf_path = get_generated_cv_path(current_user.id, pdf_filename)
    
    # Needs personal info for the PDF header
    personal_info = profile_response.personal_info
    if not personal_info:
        personal_info = PersonalInfo(name=current_user.name or "Candidate")
        
    try:
        generate_cv_pdf(tailored_cv, personal_info, str(pdf_path))
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to generate PDF: {e}"
        )
        
    # 4. Save to Database
    generated_cv = GeneratedCV(
        id=cv_id,
        user_id=current_user.id,
        profile_id=profile.id,
        job_description=data.job_description,
        job_title=data.job_title,
        company_name=data.company_name,
        tailored_content=tailored_cv.model_dump(),
        pdf_file_path=str(pdf_path),
        ats_score=tailored_cv.ats_score,
        created_at=datetime.now(timezone.utc)
    )
    db.add(generated_cv)
    await db.commit()
    await db.refresh(generated_cv)
    
    return CVResponse.model_validate(generated_cv)


@router.get(
    "/history",
    response_model=list[CVListItem],
    summary="List all generated CVs for the user",
)
async def list_generated_cvs(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> list[CVListItem]:
    """Returns a list of all tailored CVs generated by the user."""
    result = await db.execute(
        select(GeneratedCV)
        .where(GeneratedCV.user_id == current_user.id)
        .order_by(GeneratedCV.created_at.desc())
    )
    cvs = result.scalars().all()
    return [CVListItem.model_validate(cv) for cv in cvs]


@router.get(
    "/{cv_id}",
    response_model=CVResponse,
    summary="Get a specific generated CV",
)
async def get_cv(
    cv_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> CVResponse:
    """Fetch details of a specifically generated CV."""
    result = await db.execute(
        select(GeneratedCV).where(GeneratedCV.id == cv_id, GeneratedCV.user_id == current_user.id)
    )
    cv = result.scalar_one_or_none()
    
    if not cv:
        raise HTTPException(status_code=404, detail="CV not found")
        
    return CVResponse.model_validate(cv)


import os
from fastapi.responses import FileResponse

@router.get(
    "/{cv_id}/download",
    summary="Download a generated CV as PDF",
)
async def download_cv(
    cv_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> FileResponse:
    """Returns the generated PDF file for the tailored CV."""
    result = await db.execute(
        select(GeneratedCV).where(GeneratedCV.id == cv_id, GeneratedCV.user_id == current_user.id)
    )
    cv = result.scalar_one_or_none()
    
    if not cv:
        raise HTTPException(status_code=404, detail="CV not found")
        
    if not os.path.exists(cv.pdf_file_path):
        raise HTTPException(status_code=404, detail="PDF file not found on server")
        
    filename = os.path.basename(cv.pdf_file_path)
    return FileResponse(
        path=cv.pdf_file_path, 
        filename=filename, 
        media_type="application/pdf"
    )

